### ISSUE TITLE
Уязвимость в проверке прав администратора

### ISSUE THREAD

**Issue by suprunchuk** [LeoAlecksey/scripts#1]
**Описание проблемы**

В текущей реализации проверки прав администратора используется сравнение названия чата (message.chat.title), что создает потенциальную уязвимость безопасности.

```python
@bot.message_handler(commands=['admin']) # admin панель
def admin(message):
    if message.chat.title == 'Telegram Group Name IT':
        bot.send_message(chat_id=it_adm, text=f'Добрый день!\nВы в меню администратора.\nЧто Вам необходимо?\n', reply_markup=button.markup_admin())
    else:
        bot.send_message(message.chat.id,'Вы не являетесь администртором', reply_markup=button.markup_start())

```

**Суть уязвимости**
Текущая проверка основана на названии чата (chat.title)
Злоумышленник может:
Создать новый чат с идентичным названием
Добавить бота в этот чат
Получить несанкционированный доступ к админ-функциям

**Предлагаемое решение**

_Заменить проверку по названию чата на проверку по ID чата:_
```python
@bot.message_handler(commands=['admin'])
def admin(message):
    if str(message.chat.id) == it_adm:
        bot.send_message(chat_id=it_adm, text='Добрый день!\nВы в меню администратора.\nЧто Вам необходимо?\n', reply_markup=button.markup_admin())
    else:
        bot.send_message(message.chat.id, 'Вы не являетесь администратором', reply_markup=button.markup_start())
```

**Преимущества исправления**

Уникальность: ID чата является уникальным идентификатором в Telegram
Безопасность: Невозможно подделать ID чата
Надежность: ID чата не меняется при изменении названия чата

**Comment by suprunchuk** [comment]
**Как посмотреть ID в Telegram**
1. Обновите Telegram Desktop.
2. Перейдите в «Настройки».
3. Выберите «Продвинутые настройки».
4. В самом низу нажмите «Экспериментальные настройки».
5. Найдите пункт «Show Peer IDs in Profile» и включите.

Затем в it_adm = os.getenv('IT_ADM') добавьте уникальный user id

**Comment by LeoAlecksey** [comment]
Добавлен fix вышеописанной уязвимости. Спасибо @suprunchuk
